apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-demo-hpa
  namespace: reviews
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-demo
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
